version: '3'

services:




  postgres:
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=airline_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - C:\projetos\docker\postgres\data:/var/lib/postgresql/data
      - C:\projetos\docker\postgres\logs:/var/log/postgresql

  pgadmin:
    image: dpage/pgadmin4:7.0
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    volumes:
      - C:\projetos\docker\pgadmin:/var/lib/pgadmin
    ports:
      - 5080:80
    depends_on:
      - postgres


